apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-slack-status
spec:
  replicas: 1
  selector:
    matchLabels:
      name: google-slack-status
  template:
    metadata:
      labels:
        name: google-slack-status
    spec:
      serviceAccountName: google-slack-status
      containers:
        - name: google-slack-status
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - google-slack-status
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "google-slack-status"
